addons:
apt:
update: true

language: cpp

before_install:
- sudo apt update
- sudo apt install valgrind
- sudo apt install cmake
# Установка gtest
- sudo apt install libgtest-dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd -

script:
- cmake CMakeLists.txt
- make
- valgrind —leak-check=full -q ./lab_01/test.exe

after_script:
- make clean