addons:
apt:
update: true

stages:
  - build
  - memcheck
  - test

language: cpp
    
jobs:
  include:
    - stage: prebuild
        before_install:
        - sudo apt update
        - sudo apt install valgrind
        - sudo apt install cmake
        - sudo apt install libgtest-dev
        - cd /usr/src/gtest
    - stage: build
      script: sudo cmake CMakeLists.txt
      script: sudo make
      script: sudo cp *.a /usr/lib
      script: cd -
      script: mkdir build
      script: cd build
      script: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
      script: cmake --build .
      script: make

    - stage: memcheck
      script: valgrind --tool=memcheck ./lab_01 -memcheck

    - stage: test
      script: ctest --output-on-failure
    
script: make clean
