addons:
apt:
update: true

stages:
  - build
  - memcheck
  - test

language: cpp
    
jobs:
  include:
    - stage: build
      before_install: sudo apt update
      before_install: sudo apt install valgrind
      before_install: sudo apt install cmake
      before_install: sudo apt install libgtest-dev
      before_install: cd /usr/src/gtest
      before_install: sudo cmake CMakeLists.txt
      before_install: sudo make
      before_install: sudo cp *.a /usr/lib
      script: cd -
      script: mkdir build
      script: cd build
      script: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
      script: cmake --build .
      script: make

    - stage: memcheck
      script: valgrind --tool=memcheck ./lab_01 -memcheck

    - stage: test
      script: ctest --output-on-failure
      after_script: make clean
    

