addons:
apt:
update: true

stages:
  - build
  - memcheck
  - test

language: cpp
    
jobs:
  include:
    - stage: build
      install: sudo apt update
      install: sudo apt install valgrind
      install: sudo apt install cmake
      install: sudo apt install libgtest-dev
      install: sudo cmake CMakeLists.txt
      install: sudo make
      install: sudo cp *.a /usr/lib
      before_script: cd -
      before_script: mkdir build
      before_script: cd build
      script: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
      script: cmake --build .
      script: make

    - stage: memcheck
      script: valgrind --tool=memcheck ./lab_01 -memcheck

    - stage: test
      script: ctest --output-on-failure
      after_script: make clean
    

