addons:
 apt:
 update: true
 packages:
    - cmake
    - time
    - valgrind
    - libgtest-dev

stages:
  - memcheck
  - program_test

language: cpp
    
install:
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - make
    
jobs:
  include:
    - stage: memcheck
      before_script: cd -
      script: valgrind --tool=memcheck ./lab_01 -memcheck

    - stage: program_test
      before_script: cd -
      script: ctest --output-on-failure
      after_script: make clean
    

