addons:
apt:
update: true

language: cpp


before_install:
- sudo apt update
- sudo apt install valgrind
- sudo apt install cmake
- sudo apt install cppcheck
- sudo apt install libgtest-dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd -

jobs:
    stages:
    - style
    - build
    - memcheck
    - test
    include:
        stage: style
        script:
        - cppcheck .

        stage: build
        script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
        - cmake --build .
        - make

        stage: memcheck
        script:
        - valgrind --tool=memcheck ./lab_01/lab_01.exe -memcheck

        stage: test
        script:
        - ./lab_01/test_01.exe
        after_script:
        - make clean
