addons:
apt:
update: true

stages:
  - build
  - memcheck
  - test

language: cpp
    
jobs:
  include:
    - stage: build
      before_install: ./ci_scripts/install-dependencies.sh
      script: ./ci_scripts/build.sh

    - stage: memcheck
      script: valgrind --tool=memcheck ./lab_01 -memcheck

    - stage: test
      script: ctest --output-on-failure
      after_script: make clean
    

