addons:
  apt:
    update: true
    packages:
      - cppcheck
      - valgrind
      - cmake
      - build-essential
      - libgtest-dev
      - lcov

stages:
  - stylecheck
  - memcheck
  - test

language: cpp

before_install:
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib

before_script:
- cd -
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
- cmake --build .
- make
    
jobs:
  include:
    - stage: stylecheck
      before_install:
      - sudo apt update
      - sudo apt install cppcheck
      - sudo apt install libgtest-dev
      install: skip
      before_script: cppcheck --std=c++11 -q --enable=all --error-exitcode=1 .
      script: skip
    
    - stage: memcheck
      script: valgrind --tool=memcheck --leak-check=full -q ./lab_04/lab_04 -memcheck

    - stage: test
      script: ctest
      after_script: make clean